Simplify setting up the space with a little script.
contentful-labs/super-chemex-bot pull request #7
Opened 2018-05-02 15:17 UTC by realityking

2018-05-03 09:51 UTC, stefanjudis requested changes
Tiny nitpicks. :)

2018-05-03 09:51 UTC, stefanjudis commented on README.md
> + * Sign-up for Contentful if you haven't already.
It  should be `Sign up`

2018-05-03 09:51 UTC, stefanjudis commented on setup-space.js
> +const spaceData = JSON.parse(fs.readFileSync('./space.json'));
`require` would work just fine here or? :)

2018-05-07 12:53 UTC, realityking commented
@stefanjudis All adressed, please have another look.

2018-05-07 19:27 UTC, stefanjudis requested changes
Tiny nit... apart from that 👌🏻

2018-05-07 19:27 UTC, stefanjudis commented on package.json
> +  }
You're not using this one or? :)

2018-05-07 19:27 UTC, stefanjudis commented on package.json
> +  }
`pify` i mean. :)

2018-05-07 21:21 UTC, merged